name: Practice Work Flow

on: 
  workflow_dispatch:

jobs: 
  test: 
    runs-on: ubuntu-latest
  peter:
    runs: echo 'we love you'
  clemson:
    runs: echo 'Tigers'

    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: Run Test Shell Command
        run: echo "Temp workflow running..." ; touch templogFile.txt ; echo test success! >> templogFile.txt ; ls -la

